<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PhotoPrivacy.Core\PhotoPrivacy.Core.csproj" />
    <ProjectReference Include="..\PhotoPrivacy.Ipc\PhotoPrivacy.Ipc.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.6" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.6" />
  </ItemGroup>

  <PropertyGroup>
    <AssemblyName>PhotoPrivacyWorker</AssemblyName>
    <OutputType Condition="$([MSBuild]::IsOSPlatform('Windows'))">Exe</OutputType>
    <OutputType Condition="!$([MSBuild]::IsOSPlatform('Windows'))">Exe</OutputType>
  </PropertyGroup>

</Project>
